image: node:14

stages:
  - test

variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'
  pnpm_CACHE_FOLDER: '/root/.cache/pnpm'

cache:
  paths:
    - /root/.cache/
    - cache/Cypress
    - $CI_PROJECT_DIR/node_modules/
  key: ${CI_COMMIT_REF_SLUG}

test:
  stage: test
  image:
    name: cypress/included:8.7.0
    entrypoint: ['']
  script:
    - pnpm cache dir
    - cd -- "$CI_PROJECT_DIR"
    - pnpm --frozen-lockfile
    - pnpm lint
    - pnpm test:ci:components
    - pnpm build
    - pnpm preview --host --port=4000
    - pnpm test:ci:e2e
  coverage: '/Lines\s+:\s(\d+.?\d+)%/'
  artifacts:
    paths:
      - '$CI_PROJECT_DIR/tests/e2e/videos/*.mp4'
      - '$CI_PROJECT_DIR/coverage'
    expire_in: 1 weeks
    when: on_failure
  timeout: 15m
